services:
  api:
    container_name: project_dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=achieved
      - PGHOST=db
      - PGPASSWORD=projectpass
      - PGDATABASE=library
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: debug_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=library
      - POSTGRES_USER=achieved
      - POSTGRES_PASSWORD=projectpass
    
volumes:
  dbdata:
networks: 
  default:
    name: project_api
